# Do not edit this file. Put files in the dir below.
# Note: bashrc refers to something that runs in each and every new shell.
for BashRC in "$HOME"/.config/bashrc.d/*.sh ; do
    # shellcheck disable=SC1090
    source "$BashRC"
done
