[tasks.default]
    links = [
        [".bash_profile"],
        [".bashrc"],
        [".config/htop/htoprc"],
        [".gitconfig"],
        [".ssh/config"],
        ["bin/.vscode/launch.json"],
        ["bin/aws-ec2-headcount.sh"],
        ["bin/aws-iam-cleanup.sh"],
        ["bin/aws-my-ec2-status.sh"],
        ["bin/aws-owner-tag.sh"],
        ["bin/bash-tput-colours.sh"],
        ["bin/cron-monthly-cleanup.sh"],
        ["bin/do-terraform-init.sh"],
        ["bin/docker-start.sh"],
        ["bin/get-latest-k8s.sh"],
        ["bin/get-path.sh"],
        ["bin/git-branch-sync.sh"],
        ["bin/git-hub-out.sh"],
        ["xkpasswd.json"],
    ]

### Install cht.sh
#
# curl cht.sh/:intro
#
# curl https://cht.sh/:cht.sh > ~/bin/cht.sh
# chmod +x ~/bin/cht.sh
#
# mkdir -p ~/.bash.d/
# curl https://cht.sh/:bash_completion > ~/.bash.d/cht.sh
# echo 'source ~/.bash.d/cht.sh' >> ~/.bashrc
# source ~/.bash.d/cht.sh

### Capture git and go source repos
#
# tree -d -l -L 3 -o tree.src.$(gdn).txt -n /Users/jameslucktaylor/git /Users/jameslucktaylor/go/src
#
#   -d            List directories only.
#   -l            Follow symbolic links like directories.
#   -L level      Descend only level directories deep.
#   -o filename   Output to file instead of stdout.
#   -n            Turn colorization off always (-C overrides).
#
# OR
#
# find ~ -type d -name ".git" -execdir pwd \; 2>/dev/null

### Used in .bashrc
#
# git-prompt.sh -> git/github.com/lyze/posh-git-sh/git-prompt.sh
