[macros.install]
    deps = ["homebrew"]
    prefix = ["brew", "install"]

[tasks.default]
    links = [
        [".bash_profile"],
        [".bashrc"],
        [".config/htop/htoprc"],
        [".ssh/config"],
        ["bin/.vscode/launch.json"],
        ["bin/aws-ec2-headcount.sh"],
        ["bin/aws-iam-cleanup.sh"],
        ["bin/aws-my-ec2-status.sh"],
        ["bin/aws-owner-tag.sh"],
        ["bin/bash-tput-colours.sh"],
        ["bin/cron-monthly-cleanup.sh"],
        ["bin/do-terraform-init.sh"],
        ["bin/docker-start.sh"],
        ["bin/gcp-katka-du.sh"],
        ["bin/get-latest-k8s.sh"],
        ["bin/get-path.sh"],
        ["bin/git-branch-sync.sh"],
        ["bin/git-hub-out.sh"],
        ["xkpasswd.json"],
    ]

[tasks.git]
    rejects = [["stat", "/usr/local/bin/git"]]
    cmds = [["@install", "git"]]
    links = [[".gitconfig"]]

[tasks.homebrew]
    rejects = [["command", "-v", "brew"]]
    cmds = [[
        "/usr/bin/ruby", "-e",
        "$(curl --fail --location --show-error --silent https://raw.githubusercontent.com/Homebrew/install/master/install)"
    ]]

[tasks.lists]
    cmds = [
        ["${HM_SRC}/bin/homemaker/capture-git-src.sh"],
        ["${HM_SRC}/bin/homemaker/list-homebrew.sh"],
    ]

### Install cht.sh
#
# curl cht.sh/:intro
#
# curl https://cht.sh/:cht.sh > ~/bin/cht.sh
# chmod +x ~/bin/cht.sh
#
# mkdir -p ~/.bash.d/
# curl https://cht.sh/:bash_completion > ~/.bash.d/cht.sh
# echo 'source ~/.bash.d/cht.sh' >> ~/.bashrc
# source ~/.bash.d/cht.sh

### Used in .bashrc
#
# git-prompt.sh -> git/github.com/lyze/posh-git-sh/git-prompt.sh
