[macros.install]
    deps = ["homebrew"]
    prefix = ["brew", "install"]

[macros.installcask]
    deps = ["homebrew"]
    prefix = ["brew", "cask", "install"]

[tasks.default]
    deps = ["git"]
    links = [
        [".bash_profile"],
        [".bashrc"],
        [".config/htop/htoprc"],
        [".config/nano/nanorc"],
        [".nethackrc"],
        [".ssh/config"],
        [".vimrc"],
        ["bin/.vscode/launch.json"],
        ["bin/aws-ec2-headcount.sh"],
        ["bin/aws-iam-cleanup.sh"],
        ["bin/aws-my-ec2-status.sh"],
        ["bin/aws-owner-tag.sh"],
        ["bin/bash-tput-colours.sh"],
        ["bin/cron-monthly-cleanup.sh"],
        ["bin/do-terraform-init.sh"],
        ["bin/docker-start.sh"],
        ["bin/gcp-du.sh"],
        ["bin/gcp-katka-du.sh"],
        ["bin/get-latest-k8s.sh"],
        ["bin/get-path.sh"],
        ["bin/git-branch-sync.sh"],
        ["bin/git-fix-remotes.sh"],
        ["bin/git-hub-out.sh"],
        ["Library/Application Support/Code/User/settings.json"],
        ["Library/Preferences/com.googlecode.iterm2.plist"],
        ["xkpasswd.json"],
    ]

[tasks.coreutils]
    rejects = [["stat", "/usr/local/opt/coreutils"]]
    cmds = [["@install", "coreutils"]]

[tasks.git]
    rejects = [["stat", "/usr/local/bin/git"]]
    cmds = [["@install", "git"]]

[tasks.gitconfig]
    deps = ["git"]
    links = [[".gitconfig.aliases"]]
    templates = [[".gitconfig"]]

[tasks.golang]
    rejects = [["stat", "/usr/local/bin/go"]]
    envs = [["GOPATH", "${HM_DEST}/go"]]
    cmds = [
        ["mkdir", "-p", "$GOPATH"],
        ["@install", "go"],
    ]

[tasks.homebrew]
    rejects = [["command", "-v", "brew"]]
    envs = [[
        "HOMEBREWINSTALL",
        "https://raw.githubusercontent.com/Homebrew/install/master/install"
    ]]
    cmds = [["/usr/bin/ruby", "-e",
        "$(curl --fail --location --show-error --silent $HOMEBREWINSTALL)"]]

[tasks.lists]
    deps = ["lists-git", "lists-homebrew", "lists-vscode"]

[tasks.lists-git]
    deps = ["coreutils", "git"]
    cmds = [
        ["${HM_SRC}/bin/homemaker/list-git.sh"],
    ]

[tasks.lists-homebrew]
    deps = ["coreutils", "homebrew"]
    cmds = [
        ["${HM_SRC}/bin/homemaker/list-homebrew.sh"],
    ]

[tasks.lists-vscode]
    deps = ["coreutils", "vscode"]
    cmds = [
        ["${HM_SRC}/bin/homemaker/list-vscode.sh"],
    ]

[tasks.vscode]
    rejects = [["stat", "/Applications/Visual Studio Code.app"]]
    cmds = [["@installcask", "visual-studio-code"]]

### Install cht.sh
#
# curl cht.sh/:intro
#
# curl https://cht.sh/:cht.sh > ~/bin/cht.sh
# chmod +x ~/bin/cht.sh
#
# mkdir -p ~/.bash.d/
# curl https://cht.sh/:bash_completion > ~/.bash.d/cht.sh
# echo 'source ~/.bash.d/cht.sh' >> ~/.bashrc
# source ~/.bash.d/cht.sh

### Used in .bashrc
#
# git-prompt.sh -> git/github.com/lyze/posh-git-sh/git-prompt.sh
