[tasks.default]
    links = [
        [".bash_profile"],
        [".bashrc"],
        [".config/htop/htoprc"],
        [".gitconfig"],
        [".ssh/config"],
        ["bin/aws-ec2-headcount.sh"],
        ["bin/aws-iam-cleanup.sh"],
        ["bin/aws-my-ec2-status.sh"],
        ["bin/aws-owner-tag.sh"],
        ["bin/bash-tput-colours.sh"],
        ["bin/cron-monthly-cleanup.sh"],
        ["bin/do-terraform-init.sh"],
        ["bin/docker-start.sh"],
        ["bin/get-latest-k8s.sh"],
        ["bin/get-path.sh"],
        ["bin/git-branch-sync.sh"],
        ["bin/git-hub-out.sh"],
        ["xkpasswd.json"],
    ]
