[macros.install]
    deps = ["homebrew"]
    prefix = ["brew", "install"]

[macros.installcask]
    deps = ["homebrew"]
    prefix = ["brew", "cask", "install"]

[tasks.default]
    deps = ["git", "jq"]
    envs = [["ZipGoesHere", "${HM_SRC}"]]
    cmds = [["${HM_SRC}/bin/homemaker/eternal_history.sh"]]
    links = [
        [".bashrc"],
        [".config/bashrc.d/"],
        [".config/htop/htoprc"],
        [".config/nano/nanorc"],
        [".config/powershell/Microsoft.PowerShell_profile.ps1"],
        [".config/powershell/Microsoft.VSCode_profile.ps1"],
        [".config/profile.d/"],
        [".inputrc"],
        [".nethackrc"],
        [".profile"],
        [".ssh/config"],
        [".vimrc"],
        ["Library/Application Support/Code/User/keybindings.json"],
        ["Library/Application Support/Code/User/settings.json"],
        ["Library/Application Support/Code/User/snippets/"],
        ["bash-cheat-sheet.txt"],
        ["bin/"],
        ["git-completion.bash"],
        ["posh-git-prompt.sh"],
    ]

[tasks.coreutils]
    rejects = [["stat", "/usr/local/opt/coreutils"]]
    cmds = [["@install", "coreutils"]]

[tasks.git]
    rejects = [["stat", "/usr/local/bin/git"]]
    cmds = [["@install", "git"]]

[tasks.gitconfig]
    deps = ["git"]
    links = [
        [".gitconfig.aliases"],
        [".gitmessage"],
    ]
    templates = [[".gitconfig"]]

[tasks.golang]
    rejects = [["stat", "/usr/local/bin/go"]]
    envs = [["GOPATH", "${HM_DEST}/go"]]
    cmds = [
        ["mkdir", "-p", "$GOPATH"],
        ["@install", "go"],
    ]

[tasks.homebrew]
    rejects = [["command", "-v", "brew"]]
    envs = [["HOMEBREWINSTALL", "https://raw.githubusercontent.com/Homebrew/install/master/install"]]
    cmds = [["/usr/bin/ruby", "-e",
        "$(curl --fail --location --show-error --silent $HOMEBREWINSTALL)"]]

[tasks.jq]
    rejects = [["stat", "/usr/local/bin/jq"]]
    cmds = [["@install", "jq"]]

[tasks.lists]
    deps = ["lists-git", "lists-go-bin", "lists-homebrew", "lists-npm", "lists-vscode"]

[tasks.lists-git]
    deps = ["coreutils", "git"]
    cmds = [["${HM_SRC}/bin/homemaker/list-git.sh"]]

[tasks.lists-go-bin]
    deps = ["coreutils", "golang"]
    cmds = [["${HM_SRC}/bin/homemaker/list-go-bin.sh"]]

[tasks.lists-homebrew]
    deps = ["coreutils", "homebrew"]
    cmds = [["${HM_SRC}/bin/homemaker/list-homebrew.sh"]]

[tasks.lists-npm]
    deps = ["coreutils", "node"]
    cmds = [["${HM_SRC}/bin/homemaker/list-npm.sh"]]

[tasks.lists-vscode]
    deps = ["coreutils", "vscode"]
    cmds = [["${HM_SRC}/bin/homemaker/list-vscode.sh"]]

[tasks.node]
    rejects = [["stat", "/usr/local/bin/node"]]
    cmds = [["@install", "node"]]

[tasks.vscode]
    rejects = [["stat", "/Applications/Visual Studio Code.app"]]
    cmds = [["@installcask", "visual-studio-code"]]

### Install cht.sh
#
# curl cht.sh/:intro
#
# curl https://cht.sh/:cht.sh > ~/bin/cht.sh
# chmod +x ~/bin/cht.sh
#
# mkdir -p ~/.bash.d/
# curl https://cht.sh/:bash_completion > ~/.bash.d/cht.sh
# echo 'source ~/.bash.d/cht.sh' >> ~/.bashrc
# source ~/.bash.d/cht.sh

### Used in .bashrc
#
# git-prompt.sh -> git/github.com/lyze/posh-git-sh/git-prompt.sh
