version: 3

vars:
  PODMAN_IMAGES:
    # Skip images with a '<none>' tag.
    sh: >-
      podman images
      --format='{{`{{-
      if and
      (ne .Tag "<none>")
      (ne (printf "%.10s" .Repository) "localhost/")
      }}{{.Repository}}:{{.Tag}}{{end}}`}}'
      --sort=repository

tasks:
  default: task --list-all

  podman:pull:
    ignore_error: true
    interactive: true
    internal: true
    silent: true
    desc: Pull an image.
    requires:
      vars:
        - PODMAN_IMAGE
    cmd: podman pull {{.PODMAN_IMAGE}}

  # TODO: split on same repo but different tag, so downloads don't duplicate/repeat

  topgrade:podman-pull:
    desc: Pull all images in parallel.
    deps:
      - for:
          var: PODMAN_IMAGES
        task: podman:pull
        vars:
          PODMAN_IMAGE: '{{.ITEM}}'
