version: 3

vars:
  DOCKER_IMAGES:
    # Skip the Rancher Desktop proxy image, and images with a '<none>' tag.
    sh: >-
      docker images
      --format='{{`{{-
      if and
      (ne .Repository "ghcr.io/rancher-sandbox/rancher-desktop/rdx-proxy")
      (ne .Tag "<none>")
      }}{{.Repository}}:{{.Tag}}{{end}}`}}'

tasks:
  default: task --list-all

  docker:pull:
    ignore_error: true
    interactive: true
    internal: true
    silent: true
    desc: Pull a Docker image.
    requires:
      vars:
        - DOCKER_IMAGE
    cmd: docker pull {{.DOCKER_IMAGE}}

  # TODO: split on same repo but different tag, so downloads don't duplicate/repeat

  topgrade:docker-pull:
    desc: Pull all Docker images in parallel.
    deps:
      - for:
          var: DOCKER_IMAGES
        task: docker:pull
        vars:
          DOCKER_IMAGE: '{{.ITEM}}'

  ### Chezmoi data file and its JSON Schema.

  jq-fmt:chezmoidata:
    desc: Run the chezmoidata JSON Schema through jq to format it.
    cmds:
      - jq . chezmoidata.schema.json > chezmoidata.schema.json.tmp
      - rm chezmoidata.schema.json
      - mv chezmoidata.schema.json.tmp chezmoidata.schema.json

  jv:chezmoidata:
    desc: Run the chezmoidata file through jv to validate it against the JSON Schema.
    cmd: jv --output=detailed chezmoidata.schema.json .chezmoidata.yaml

  chezmoidata:
    desc: Format the chezmoidata JSON Schema, and validate the '.chezmoidata.yaml' file with it.
    cmds:
      - task: jq-fmt:chezmoidata
      - task: jv:chezmoidata
