# # Commands to run before anything.
# [pre_commands]
# "Before: disconnect ZTNA" = "warp-cli disconnect && sleep 1"

# # Commands to run after anything.
# [post_commands]
# "After: connect ZTNA" = "warp-cli connect"

# Custom commands.
[commands]
"Pull Docker images in parallel" = "mise exec --verbose -- task --global topgrade:docker-pull"

[misc]
# Don't ask for confirmations
#assume_yes = true

# Disable specific steps - same options as the command line flag
#disable = ["system", "emacs"]

# Ignore failures for these steps
#ignore_failures = [
#  "containers",
#]

# Run specific steps - same options as the command line flag
# only = ["containers"]
only = [
  "brew_cask",
  "brew_formula",
  "cargo",
  # "containers", # Quicker to pull in parallel with the custom command and global Taskfile.
  "custom_commands",
  "gcloud",
  "github_cli_extensions",
  "go",
  "helm",
  "krew",
  "mise",
  "pip3",
  "pnpm",
  "rustup",
  "system",
  # "vscode", # Can be handled in-app, and toggling ZTNA just for this is disruptive.
]

# Display the time in step titles
display_time = true

# Cleanup temporary or old files
cleanup = true

# Skip sending a notification at the end of a run
skip_notify = true

[brew]
autoremove = true
