# Commands to run before anything.
[pre_commands]
"Before: disconnect ZTNA" = "warp-cli disconnect && sleep 1"

# Commands to run after anything.
[post_commands]
"After: connect ZTNA" = "warp-cli connect"

[misc]
# Don't ask for confirmations
#assume_yes = true

# Disable specific steps - same options as the command line flag
#disable = ["system", "emacs"]

# Ignore failures for these steps
#ignore_failures = [
#  "containers",
#]

# Run specific steps - same options as the command line flag
# only = ["containers"]
only = [
  "brew_cask",
  "brew_formula",
  "cargo",
  "containers",
  "gcloud",
  "github_cli_extensions",
  "go",
  "helm",
  "krew",
  "mas",
  "mise",
  "pip3",
  "pnpm",
  "rustup",
  "system",
  "vscode",
]

# Display the time in step titles
display_time = true

# Cleanup temporary or old files
cleanup = true

# Skip sending a notification at the end of a run
skip_notify = true

[brew]
autoremove = true

[containers]
# Specify the containers to ignore while updating (wildcard supported)
ignored_containers = [
  "europe-west1-docker.pkg.dev/ovo-bedrock-dev/sapling-jl-go/evergreen-sapling-go:*",
  "ghcr.io/rancher-sandbox/rancher-desktop/rdx-proxy:latest",
]
