# Don't ask for confirmations
#assume_yes = true

# Disable specific steps - same options as the command line flag
#disable = ["system", "emacs"]

# Ignore failures for these steps
#ignore_failures = ["powershell"]

# Run specific steps - same options as the command line flag
# only = ["containers"]
only = [
  "brew_formula",
  "brew_cask",
  "rustup",
  "cargo",
  "pip3",
  "gcloud",
  "github_cli_extensions",
]

# Display the time in step titles
display_time = true

# Cleanup temporary or old files
cleanup = true

# Skip sending a notification at the end of a run
skip_notify = true
